{
 "title": "API monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total request",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "total_call_total" }
   ]
  },
  {
   "title": "Successed request",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "successed_call_total" }
   ]
  },
  {
   "title": "Failed request",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "failed_call_total" }
   ]
  },
  {
   "title": "Total CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "cpu",
   "valueName": "avg",
   "targets": [
    { "expr": "sum (machine_cpu_cores)" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "cpu",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_user_seconds_total{name=\"apitest_api_1\"}[1m])) by (apitest_api_1)",
     "legendFormat": "{{name }}"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "machine_memory_bytes" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"apitest_api_1\"})"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{name=\"apitest_api_1\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{name=\"apitest_api_1\"}[1m])) / sum (machine_cpu_cores) * 100",
     "legendFormat": "apitest_api_1"
    }
   ]
  }
 ]
}